name: Destroy ECS Resources

on:
  workflow_dispatch:  # Manual trigger

jobs:
  destroy-ecs:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Set desired count to 0 (if service exists)
        run: |
          aws ecs update-service \
            --cluster flask-cluster \
            --service flask-service \
            --desired-count 0 || echo "Service not found or already deleted"

      - name: Delete ECS service
        run: |
          aws ecs delete-service \
            --cluster flask-cluster \
            --service flask-service \
            --force || echo "Service not found or already deleted"

      - name: Delete ECS cluster
        run: |
          aws ecs delete-cluster \
            --cluster flask-cluster || echo "Cluster not found or already deleted"

